apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
  namespace: first-namespace
  labels:
    app: second-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-deployment
  template:
    metadata:
      labels:
        app: second-deployment
    spec:
      containers:
       - name: nginx-container
         image: 'nginx:1.20.2'
         ports:
         - containerPort: 80
