apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: logger-container
    image: busybox
    command: ["sh", "-c", "while true; do echo hello from the logger container; sleep 3600; done"]
